In [1]:
import pandas as pd
import numpy as np

# Load data in chunks to avoid memory error
chunk_size = 100000
chunks = []

for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
    chunks.append(chunk)

df = pd.concat(chunks, ignore_index=True)

df.head(10)

C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (44) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,26,27,28,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,26,27,28,37,38,39,41,42,43,44,45,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,26,27,28,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (8,9,24,26,27,28,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (8,9,24,26,27,28,33,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (8,9,24,26,27,28,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,26,27,28,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,26,27,28,33,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (8,9,24,26,27,28,29,33,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,26,27,28,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,26,27,28,33,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,26,27,28,33,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,26,27,28,33,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,26,27,28,33,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,26,27,28,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (29,33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,26,27,28,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,26,27,28,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,26,27,28,33,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,26,27,28,33,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (8,9,24,26,27,28,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (8,9,24,26,27,28,33,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,26,27,28,33,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,26,27,28,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (45) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (26,27,33,45) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,28,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):
C:\Users\leoba\AppData\Local\Temp\ipykernel_18932\636725227.py:8: DtypeWarning: Columns (24,26,27,28,37,38,39,41,42,43,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv("../scripts/data/AirNow_AQS_Meteo_Joined_Jan2020-Oct2025.csv", chunksize=chunk_size):

,0,1,2,3,4,5,6,7,8,9,...,Owning Agency,Local Site Name,Address,Zip Code,State Name,County Name,City Name,CBSA Name,Tribe Name,Extraction Date
0,32.579361,-116.929486,2020-01-01T00:00,OZONE,35.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31
1,32.579361,-116.929486,2020-01-01T01:00,OZONE,33.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31
2,32.579361,-116.929486,2020-01-01T02:00,OZONE,29.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31
3,32.579361,-116.929486,2020-01-01T03:00,OZONE,29.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31
4,32.579361,-116.929486,2020-01-01T04:00,OZONE,27.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31
5,32.579361,-116.929486,2020-01-01T05:00,OZONE,26.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31
6,32.579361,-116.929486,2020-01-01T06:00,OZONE,28.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31
7,32.579361,-116.929486,2020-01-01T07:00,OZONE,31.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31
8,32.579361,-116.929486,2020-01-01T08:00,OZONE,33.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31
9,32.579361,-116.929486,2020-01-01T09:00,OZONE,32.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31

## Change Column Names for easier analysis and processing

In [2]:
df.rename(columns={'0' : 'latitude', '1': 'longitude', '2': 'utc', '3': 'parameter', '4': 'concentration',
                   '5': "unit", '6': "sitename", '7': "agencyname", '8': "fullaqscode", '9': "intlaqscode"}, inplace=True)

shape = df.shape
print(f"{shape}")

df.head(10)

(12371401, 47)

,latitude,longitude,utc,parameter,concentration,unit,sitename,agencyname,fullaqscode,intlaqscode,...,Owning Agency,Local Site Name,Address,Zip Code,State Name,County Name,City Name,CBSA Name,Tribe Name,Extraction Date
0,32.579361,-116.929486,2020-01-01T00:00,OZONE,35.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31
1,32.579361,-116.929486,2020-01-01T01:00,OZONE,33.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31
2,32.579361,-116.929486,2020-01-01T02:00,OZONE,29.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31
3,32.579361,-116.929486,2020-01-01T03:00,OZONE,29.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31
4,32.579361,-116.929486,2020-01-01T04:00,OZONE,27.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31
5,32.579361,-116.929486,2020-01-01T05:00,OZONE,26.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31
6,32.579361,-116.929486,2020-01-01T06:00,OZONE,28.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31
7,32.579361,-116.929486,2020-01-01T07:00,OZONE,31.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31
8,32.579361,-116.929486,2020-01-01T08:00,OZONE,33.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31
9,32.579361,-116.929486,2020-01-01T09:00,OZONE,32.0,PPB,Otay Mesa - Donovan,San Diego APCD,60731014,840060731014,...,San Diego County Air Pollution Control District,Donovan,"480 ALTA RD, OTAY MESA, CA",92154.0,California,San Diego,Otay Mesa,"San Diego-Carlsbad, CA",NaN,2025-07-31

### Keep only relevant columns

In [3]:
df = df.drop(columns=[
    'Latitude',
    'Longitude',
    'utc',
    'UTC_hour',
    # 'sitename',
    'agencyname',
    # 'fullaqscode',
    'intlaqscode',
    'Datum',
    'Elevation',
    'Land Use',
    'Location Setting',
    'Site Established Date',
    'Site Closed Date',
    'Met Site State Code',
    'Met Site County Code',
    'Met Site Site Number',
    'Met Site Type',
    'Met Site Distance',
    'Met Site Direction',
    'GMT Offset',
    'Owning Agency',
    'Local Site Name',
    'Address',
    'Zip Code',
    'State Name',
    # 'County Name',
    'City Name',
    'CBSA Name',
    'Tribe Name',
    'Extraction Date',
    'State Code',
    'County Code',
    'Site Number',
    'unit'
])

shape = df.shape
print(f"{shape}")

df.head(10)

(12371401, 15)

,latitude,longitude,parameter,concentration,sitename,fullaqscode,UTC,temperature_2m,precipitation,weather_code,wind_speed_10m,wind_direction_10m,wind_gusts_10m,relative_humidity_2m,County Name
0,32.579361,-116.929486,OZONE,35.0,Otay Mesa - Donovan,60731014,2020-01-01 00:00:00+00:00,16.774500,0.0,0.0,5.804825,299.744780,15.48,65.068270,San Diego
1,32.579361,-116.929486,OZONE,33.0,Otay Mesa - Donovan,60731014,2020-01-01 01:00:00+00:00,16.374498,0.0,0.0,4.104631,344.744800,7.92,51.225185,San Diego
2,32.579361,-116.929486,OZONE,29.0,Otay Mesa - Donovan,60731014,2020-01-01 02:00:00+00:00,14.424500,0.0,0.0,5.692100,108.435040,7.20,55.308056,San Diego
3,32.579361,-116.929486,OZONE,29.0,Otay Mesa - Donovan,60731014,2020-01-01 03:00:00+00:00,11.324500,0.0,0.0,9.904906,109.093590,13.32,64.299350,San Diego
4,32.579361,-116.929486,OZONE,27.0,Otay Mesa - Donovan,60731014,2020-01-01 04:00:00+00:00,10.024500,0.0,0.0,10.182337,98.130020,14.04,64.229520,San Diego
5,32.579361,-116.929486,OZONE,26.0,Otay Mesa - Donovan,60731014,2020-01-01 05:00:00+00:00,8.574500,0.0,0.0,9.779817,96.340096,14.40,70.065970,San Diego
6,32.579361,-116.929486,OZONE,28.0,Otay Mesa - Donovan,60731014,2020-01-01 06:00:00+00:00,7.974500,0.0,0.0,7.695920,100.784256,13.32,71.446540,San Diego
7,32.579361,-116.929486,OZONE,31.0,Otay Mesa - Donovan,60731014,2020-01-01 07:00:00+00:00,8.674500,0.0,0.0,11.792404,102.339070,14.40,63.920403,San Diego
8,32.579361,-116.929486,OZONE,33.0,Otay Mesa - Donovan,60731014,2020-01-01 08:00:00+00:00,7.974500,0.0,0.0,12.964998,91.591110,18.00,67.987620,San Diego
9,32.579361,-116.929486,OZONE,32.0,Otay Mesa - Donovan,60731014,2020-01-01 09:00:00+00:00,7.024500,0.0,0.0,13.755580,96.008920,19.80,72.541306,San Diego

### Pivot the data to have pollutants as columns

In [4]:
location_lookup = df.groupby(['latitude', 'longitude']).agg({'sitename': 'first', 'fullaqscode': 'first', 'County Name': 'first'}).reset_index()

location_lookup.head(10)

,latitude,longitude,sitename,fullaqscode,County Name
0,32.579361,-116.929486,Otay Mesa - Donovan,60731014,San Diego
1,32.629200,-115.446900,Universidad Autonoma de Baja California,800020012,BAJA CALIFORNIA NORTE
2,32.631229,-117.059074,Chula Vista,60730001,San Diego
3,32.633600,-115.504200,SPABC14 COBACH,800020014,BAJA CALIFORNIA NORTE
4,32.676180,-115.483070,Calexico - Ethel Street,60250005,Imperial
5,32.710177,-117.142665,San Diego - Sherman Elementary School,840060731026,None
6,32.725190,-116.364410,La Posta Band of Indians,840060739991,None
7,32.735500,-116.345400,Manzanita Tribe 1,60732000,San Diego
8,32.750400,-116.331500,Manzanita Tribe 2,840060732097,None
9,32.789561,-116.944222,El Cajon - Lexington Elementary School,60731022,San Diego

In [5]:
df = df.pivot_table(index=['latitude', 'longitude', 'UTC', 'temperature_2m', 'precipitation', 'weather_code', 'wind_speed_10m', 'wind_direction_10m', 'wind_gusts_10m', 'relative_humidity_2m'], columns='parameter', values='concentration').reset_index()

df.columns.name = None  # Remove the columns name

shape = df.shape
print(f"{shape}")

df.head(10)

(5479683, 16)

,latitude,longitude,UTC,temperature_2m,precipitation,weather_code,wind_speed_10m,wind_direction_10m,wind_gusts_10m,relative_humidity_2m,CO,NO2,OZONE,PM10,PM2.5,SO2
0,32.579361,-116.929486,2020-01-01 00:00:00+00:00,16.774500,0.0,0.0,5.804825,299.744780,15.48,65.068270,NaN,NaN,35.0,NaN,NaN,NaN
1,32.579361,-116.929486,2020-01-01 01:00:00+00:00,16.374498,0.0,0.0,4.104631,344.744800,7.92,51.225185,NaN,NaN,33.0,NaN,NaN,NaN
2,32.579361,-116.929486,2020-01-01 02:00:00+00:00,14.424500,0.0,0.0,5.692100,108.435040,7.20,55.308056,NaN,NaN,29.0,NaN,NaN,NaN
3,32.579361,-116.929486,2020-01-01 03:00:00+00:00,11.324500,0.0,0.0,9.904906,109.093590,13.32,64.299350,NaN,NaN,29.0,NaN,NaN,NaN
4,32.579361,-116.929486,2020-01-01 04:00:00+00:00,10.024500,0.0,0.0,10.182337,98.130020,14.04,64.229520,NaN,NaN,27.0,NaN,NaN,NaN
5,32.579361,-116.929486,2020-01-01 05:00:00+00:00,8.574500,0.0,0.0,9.779817,96.340096,14.40,70.065970,NaN,NaN,26.0,NaN,NaN,NaN
6,32.579361,-116.929486,2020-01-01 06:00:00+00:00,7.974500,0.0,0.0,7.695920,100.784256,13.32,71.446540,NaN,NaN,28.0,NaN,NaN,NaN
7,32.579361,-116.929486,2020-01-01 07:00:00+00:00,8.674500,0.0,0.0,11.792404,102.339070,14.40,63.920403,NaN,NaN,31.0,NaN,NaN,NaN
8,32.579361,-116.929486,2020-01-01 08:00:00+00:00,7.974500,0.0,0.0,12.964998,91.591110,18.00,67.987620,NaN,NaN,33.0,NaN,NaN,NaN
9,32.579361,-116.929486,2020-01-01 09:00:00+00:00,7.024500,0.0,0.0,13.755580,96.008920,19.80,72.541306,NaN,NaN,32.0,NaN,NaN,NaN

In [6]:
df = df.merge(location_lookup, on=['latitude', 'longitude'], how='left')

shape = df.shape
print(f"{shape}")

df.head(10)

(5479683, 19)

,latitude,longitude,UTC,temperature_2m,precipitation,weather_code,wind_speed_10m,wind_direction_10m,wind_gusts_10m,relative_humidity_2m,CO,NO2,OZONE,PM10,PM2.5,SO2,sitename,fullaqscode,County Name
0,32.579361,-116.929486,2020-01-01 00:00:00+00:00,16.774500,0.0,0.0,5.804825,299.744780,15.48,65.068270,NaN,NaN,35.0,NaN,NaN,NaN,Otay Mesa - Donovan,60731014,San Diego
1,32.579361,-116.929486,2020-01-01 01:00:00+00:00,16.374498,0.0,0.0,4.104631,344.744800,7.92,51.225185,NaN,NaN,33.0,NaN,NaN,NaN,Otay Mesa - Donovan,60731014,San Diego
2,32.579361,-116.929486,2020-01-01 02:00:00+00:00,14.424500,0.0,0.0,5.692100,108.435040,7.20,55.308056,NaN,NaN,29.0,NaN,NaN,NaN,Otay Mesa - Donovan,60731014,San Diego
3,32.579361,-116.929486,2020-01-01 03:00:00+00:00,11.324500,0.0,0.0,9.904906,109.093590,13.32,64.299350,NaN,NaN,29.0,NaN,NaN,NaN,Otay Mesa - Donovan,60731014,San Diego
4,32.579361,-116.929486,2020-01-01 04:00:00+00:00,10.024500,0.0,0.0,10.182337,98.130020,14.04,64.229520,NaN,NaN,27.0,NaN,NaN,NaN,Otay Mesa - Donovan,60731014,San Diego
5,32.579361,-116.929486,2020-01-01 05:00:00+00:00,8.574500,0.0,0.0,9.779817,96.340096,14.40,70.065970,NaN,NaN,26.0,NaN,NaN,NaN,Otay Mesa - Donovan,60731014,San Diego
6,32.579361,-116.929486,2020-01-01 06:00:00+00:00,7.974500,0.0,0.0,7.695920,100.784256,13.32,71.446540,NaN,NaN,28.0,NaN,NaN,NaN,Otay Mesa - Donovan,60731014,San Diego
7,32.579361,-116.929486,2020-01-01 07:00:00+00:00,8.674500,0.0,0.0,11.792404,102.339070,14.40,63.920403,NaN,NaN,31.0,NaN,NaN,NaN,Otay Mesa - Donovan,60731014,San Diego
8,32.579361,-116.929486,2020-01-01 08:00:00+00:00,7.974500,0.0,0.0,12.964998,91.591110,18.00,67.987620,NaN,NaN,33.0,NaN,NaN,NaN,Otay Mesa - Donovan,60731014,San Diego
9,32.579361,-116.929486,2020-01-01 09:00:00+00:00,7.024500,0.0,0.0,13.755580,96.008920,19.80,72.541306,NaN,NaN,32.0,NaN,NaN,NaN,Otay Mesa - Donovan,60731014,San Diego

## Clean negative values

In [7]:
pollutants = ['PM2.5', 'OZONE', 'NO2', 'SO2', 'CO', 'PM10']

for pollutant in pollutants:
    if pollutant in df.columns:
        df[pollutant] = df[pollutant].mask(df[pollutant] < 0, np.nan)

df.to_pickle("../scripts/data/checkpoint_after_cleaning.pkl")